var express = require('express');
var router = express.Router();
const User = require('../models/user');

/**
 * @api {get} /users/ Request all users
 * @apiName GetUsers
 * @apiGroup User
 *
 *
 * @apiSuccess {String} username Username of the user
 * @apiSuccess {String} firstName First name of the user
 * @apiSuccess {String} lastName Last name of the user
 * @apiSuccess {String} role Role of the user "citizen" or "manager"
 * @apiSuccess {Date} createdAt Date of creation of the user
 */

/* GET users listing. */
router.get('/', function(req, res, next) {
User.find().sort('username').exec(function(err, users) {
    if (err) {
      return next(err);
    }
    res.send(users);
  });
});

/**
 * @api {post} /users/ Create a user
 * @apiName Create a user
 * @apiGroup User
 *
 * @apiSuccess {String} id A unique identifier for the user generated by the server
 * @apiSuccess {String} firstName First name of the user
 * @apiSuccess {String} lastName Last name of the user
 * @apiSuccess {String} role Role of the user "citizen" or "manager"
 * @apiSuccess {Date} createdAt Date of creation of the user
 *
 */

/* POST new user */
router.post('/', function(req, res, next) {
  // Create a new document from the JSON in the request body
  const newUser = new User(req.body);

  newUser.createdAt = Date.now();
  // Save that document
  newUser.save(function(err, savedUser) {
    if (err) {
      return next(err);
    }
    // Send the saved document in the response
    res.status(201);
    res.send(savedUser);
  });
});

module.exports = router;
